name: flutter_training
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta
  flutter: ^3.38.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  json_annotation: ^4.9.0
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training-template.git
      ref: main
      path: packages/yumemi_weather

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  yumemi_lints: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
